j0k3r/f43.me

src/FeedBundle/DataFixtures/MongoDB/LoadFeedData.php
src/FeedBundle/Document/Feed.php
src/FeedBundle/DomDocument/XDOMElement.php
src/FeedBundle/Form/Type/FeedType.php
src/FeedBundle/Formatter/RssFormatter.php
src/FeedBundle/Tests/Controller/FeedControllerTest.php

Handle feeddly custom webfeeds

---

src/FeedBundle/Extractor/Instagram.php
src/FeedBundle/Extractor/Twitter.php
src/FeedBundle/Tests/Extractor/TwitterTest.php

Handle mobile.twitter.com

---

src/FeedBundle/Extractor/Github.php
src/FeedBundle/Tests/Extractor/GithubTest.php

Handle issue & PR from Github

---

composer.json
composer.lock
src/FeedBundle/Command/FetchItemsCommand.php
src/FeedBundle/Controller/FeedItemController.php
src/FeedBundle/Controller/FeedTestController.php
src/FeedBundle/Resources/config/services.yml
src/FeedBundle/Services/ContentExtractor.php
src/FeedBundle/Tests/Services/ContentExtractorTest.php

Content extractor

---

src/FeedBundle/Extractor/Rue89.php
src/FeedBundle/Improver/Nothing.php
src/FeedBundle/Resources/config/services.yml
src/FeedBundle/Tests/Extractor/Rue89Test.php

Since they now use an api to display content on their website.
Fix #56

Add custom extract for Rue89

---

app/config/security.yml
src/FeedBundle/Controller/FeedTestController.php
src/FeedBundle/Form/Type/ItemTestType.php
src/FeedBundle/Resources/config/services.yml
src/FeedBundle/Resources/public/js/app.js
src/FeedBundle/Resources/sass/app.sass
src/FeedBundle/Resources/views/FeedTest/index.html.twig
src/FeedBundle/Resources/views/layout.html.twig
src/FeedBundle/Tests/Controller/FeedTestControllerTest.php

Anon user will now has ability to test a link and also provide a site configuration.
It'll allow every one to test a site configuration before submitting it.

Allow user to test a custom siteconfig

---

app/config/config.yml
src/FeedBundle/Command/FetchItemsCommand.php
src/FeedBundle/Content/Extractor.php
src/FeedBundle/Content/Import.php
src/FeedBundle/Controller/FeedController.php
src/FeedBundle/Controller/FeedTestController.php
src/FeedBundle/Document/Feed.php
src/FeedBundle/Document/FeedItem.php
src/FeedBundle/Document/FeedLog.php
src/FeedBundle/Extractor/AbstractExtractor.php
src/FeedBundle/Resources/config/services.yml
src/FeedBundle/Tests/Command/FetchItemsCommandTest.php
src/FeedBundle/Tests/Content/ExtractorTest.php
src/FeedBundle/Tests/Controller/FeedTestControllerTest.php
src/FeedBundle/Tests/Xml/RenderTest.php
src/FeedBundle/Tests/Xml/SimplePieProxyTest.php
src/FeedBundle/Xml/Formatter/AtomFormatter.php
src/FeedBundle/Xml/Formatter/Formatter.php
src/FeedBundle/Xml/Formatter/RssFormatter.php
src/FeedBundle/Xml/Render.php
src/FeedBundle/Xml/SimplePieProxy.php

I started this branch to fix this issue https://github.com/j0k3r/f43.me/issues/63
And finally, I moved stuff and the problem wasn't in f43me but in graby

Extract stuff from command and move it to a service

---

src/FeedBundle/Extractor/Imgur.php
src/FeedBundle/Tests/Extractor/ImgurTest.php

I still think url from Imgur are really fucked up 😒

Allow /new in Imgur url

---

composer.json
composer.lock
src/FeedBundle/Extractor/Reddituploads.php
src/FeedBundle/Resources/config/extractors.yml
src/FeedBundle/Tests/Extractor/ReddituploadsTest.php

Reddituploads

---

src/FeedBundle/Extractor/Rue89.php
tests/FeedBundle/Extractor/Rue89Test.php

Fix https://github.com/j0k3r/f43.me/issues/89

Fix Rue89 blog API

---

README.md
app/config/parameters.yml.dist
app/config/parameters.yml.travis
bin/symfony_requirements
composer.json
composer.lock
src/FeedBundle/Extractor/Flickr.php
src/FeedBundle/Resources/config/extractors.yml
tests/FeedBundle/Extractor/FlickrTest.php
tests/FeedBundle/Xml/RenderTest.php
var/SymfonyRequirements.php

Should fix https://github.com/j0k3r/f43.me/issues/95
- Use Flickr oEmbed and remove Flickr API (and the api key too).
- Update deps and update test to remove call to `getMock()`

Flickr update

---

src/FeedBundle/Extractor/Giphy.php
src/FeedBundle/Resources/config/extractors.yml
tests/FeedBundle/Extractor/GiphyTest.php

Add Giphy extractor

---

README.md
app/config/parameters.yml.dist
src/FeedBundle/Extractor/Twitch.php
src/FeedBundle/Resources/config/extractors.yml
tests/FeedBundle/Extractor/TwitchTest.php

Add Twitch extractor

---

src/FeedBundle/Extractor/Imgur.php

Update regex to better match Imgur url

Update Imgur regex

---

README.md
app/config/config.yml
app/config/config_dev.yml
app/config/config_prod.yml
app/config/routing.yml
app/config/routing_dev.yml
app/config/security.yml
src/FeedBundle/Document/Feed.php
src/FeedBundle/Document/FeedItem.php
src/FeedBundle/Document/FeedLog.php

From https://github.com/j0k3r/f43.me/pull/104
- Fix ODM annotations (String, Int, etc .. are restricted in PHP7)
- Remove extra spaces in config

Backport some fix from the PHP7 PR

---

app/config/parameters.yml.travis
tests/FeedBundle/Extractor/CamplusTest.php
tests/FeedBundle/Extractor/DailymotionTest.php
tests/FeedBundle/Extractor/DeviantartTest.php
tests/FeedBundle/Extractor/FlickrTest.php
tests/FeedBundle/Extractor/GfycatTest.php
tests/FeedBundle/Extractor/GiphyTest.php
tests/FeedBundle/Extractor/GithubTest.php
tests/FeedBundle/Extractor/HackerNewsTest.php
tests/FeedBundle/Extractor/IftttTest.php
tests/FeedBundle/Extractor/InstagramTest.php
tests/FeedBundle/Extractor/Rue89Test.php
tests/FeedBundle/Extractor/SoundcloudTest.php
tests/FeedBundle/Extractor/SpotifyTest.php
tests/FeedBundle/Extractor/StreamableTest.php
tests/FeedBundle/Extractor/TumblrTest.php
tests/FeedBundle/Extractor/TwitchTest.php
tests/FeedBundle/Extractor/VidmeTest.php
tests/FeedBundle/Extractor/VimeoTest.php
tests/FeedBundle/Extractor/VineTest.php
tests/FeedBundle/Extractor/YoutubeTest.php
tests/FeedBundle/Parser/ExternalTest.php

Backport some changes from the PHP7 PR (https://github.com/j0k3r/f43.me/pull/104)

Travis'n'tests

---

src/FeedBundle/Document/Feed.php
src/FeedBundle/Document/FeedItem.php
src/FeedBundle/Document/FeedLog.php

So using `@Field(type="date")` every where

ODM\Date will be deprecated

---

src/FeedBundle/Extractor/Twitter.php
tests/FeedBundle/Extractor/TwitterTest.php

- use `extended` mode to get the full text (and not the truncated one)
- convert hashtags, user mentions and urls to real links
- handle quoted status

Improve tweet display

---

README.md
app/config/parameters.yml.dist
app/config/parameters.yml.docker
app/config/parameters.yml.travis
src/FeedBundle/Parser/External.php
src/FeedBundle/Resources/config/parsers.yml
src/FeedBundle/Resources/views/Feed/public.html.twig
tests/FeedBundle/Parser/ExternalTest.php

Should fix https://github.com/j0k3r/f43.me/issues/113

Switch to Mercury since Readability is shutting down

---

composer.lock
src/FeedBundle/Improver/Reddit.php
tests/FeedBundle/Improver/RedditTest.php
var/SymfonyRequirements.php

Looks like reddit.com no redirect to www.reddit.com

Fix Reddit Improver

---

src/FeedBundle/Converter/Instagram.php
tests/FeedBundle/Converter/InstagramTest.php

It'll better match an instagram url.
Also, it won't match false positive url (with an user starting with a `p`)

Update converter instagram regex

---

README.md
app/config/parameters.yml.dist
app/config/parameters.yml.travis
docker/launch-f43me.sh
src/FeedBundle/Extractor/Github.php
src/FeedBundle/Resources/config/extractors.yml
tests/FeedBundle/Extractor/GithubTest.php

Fix https://github.com/j0k3r/f43.me/issues/132

Use a GitHub app to avoid rate limit

---

composer.json
composer.lock

Mostly to retrieve new versions of graby & graby-site-config

Update deps (for graby*)

---

src/FeedBundle/Converter/Twitter.php
src/FeedBundle/Extractor/Twitter.php
src/FeedBundle/Resources/config/converters.yml
tests/FeedBundle/Converter/TwitterTest.php

It converts pic.twitter.com image to real image (which can be viewed) and also it transform t.co link to real link
Fix https://github.com/j0k3r/f43.me/issues/123

Add Twitter converter

---

composer.lock
docker/Dockerfile-php7.0
docker/Dockerfile-php7.1
src/FeedBundle/Extractor/HackerNews.php
src/FeedBundle/Improver/ImproverChain.php
tests/FeedBundle/Extractor/HackerNewsTest.php
tests/FeedBundle/Improver/ImproverChainTest.php

- update deps
- fix zip installation in docker
- fix bad host filtering
- fix when HN api doesn't return a `text` field

Fix some HackerNews issues

---

src/FeedBundle/Extractor/Gfycat.php
tests/FeedBundle/Extractor/GfycatTest.php

when they contains `gifs/detail/`

Fix gfycat url

---

src/FeedBundle/Extractor/RedditImage.php
src/FeedBundle/Extractor/RedditPost.php
src/FeedBundle/Extractor/RedditVideo.php
src/FeedBundle/Resources/config/extractors.yml
tests/FeedBundle/Extractor/HackerNewsTest.php
tests/FeedBundle/Extractor/PeriscopeTest.php
tests/FeedBundle/Extractor/RedditImageTest.php
tests/FeedBundle/Extractor/RedditPostTest.php
tests/FeedBundle/Extractor/RedditVideoTest.php

- Rename reddit image
- Add reddit video
- Add reddit post

Reddit video / image / post

---

app/config/parameters.yml.dist
app/config/parameters.yml.docker
app/config/parameters.yml.travis
composer.lock

- Define User-Agent to avoid errors
- Update deps

Some fixes after last PR

---

composer.lock
src/FeedBundle/Form/Type/ItemTestType.php

There were no validation on the url field. So entering a random value generated an error later in the parsing process.

Url validation

---

src/FeedBundle/Extractor/RedditVideo.php
tests/FeedBundle/Extractor/RedditVideoTest.php

The way it was build worked from the debug page but not from the RSS feed (which is the mostly common use …)

Fix video fetching from RSS

---

src/AppBundle/Extractor/Gfycat.php

Looks like the API url has changed recently

Fix Gfycat API url

---

app/config/parameters.yml.docker
docker-compose.yml
docker/Dockerfile-php7.2

Jump to PHP 7.2 for the docker image

Update Docker to PHP 7.2

---

composer.lock
src/AppBundle/Content/Extractor.php
src/AppBundle/Controller/FeedTestController.php
src/AppBundle/Parser/AbstractParser.php
src/AppBundle/Parser/External.php
src/AppBundle/Parser/Internal.php
tests/AppBundle/Command/FetchItemsCommandTest.php
tests/AppBundle/Command/RemoveItemsCommandTest.php

I discovered that the testing part of f43.me wasn't really bullet proof and should not work in some case.
This PR fix that.

Fix testing part of SiteConfig

---

composer.lock
src/AppBundle/Extractor/Giphy.php
src/AppBundle/Form/Type/FeedType.php
src/AppBundle/Form/Type/ItemTestType.php
tests/AppBundle/Extractor/GiphyTest.php

Fix Giphy image/url parameter

---

.travis.yml
composer.json
composer.lock
phpstan.neon
src/AppBundle/Command/FetchItemsCommand.php
src/AppBundle/Command/RemoveItemsCommand.php
src/AppBundle/Controller/FeedController.php
src/AppBundle/Controller/FeedItemController.php
src/AppBundle/Controller/FeedLogController.php
src/AppBundle/Document/Feed.php
src/AppBundle/Document/FeedItem.php
src/AppBundle/Document/FeedLog.php
src/AppBundle/DomDocument/XDOMDocument.php
src/AppBundle/Extractor/AbstractExtractor.php
src/AppBundle/Repository/FeedItemRepository.php
src/AppBundle/Repository/FeedLogRepository.php
src/AppBundle/Validator/Constraints/ConstraintRss.php
src/AppBundle/Validator/Constraints/ConstraintRssValidator.php
src/AppBundle/Xml/Formatter/Formatter.php
tests/AppBundle/Command/FetchItemsCommandTest.php
tests/AppBundle/Content/ExtractorTest.php
tests/AppBundle/Extractor/FlickrTest.php
tests/AppBundle/Validator/ConstraintRssValidatorTest.php
tests/AppBundle/Xml/RenderTest.php

Enable PHPStan

---

composer.lock
docker/Dockerfile-php7.2
src/AppBundle/Extractor/Github.php

Also:
- fix the Docker image
- update deps

Fix GitHub headers

---

app/config/config.yml

So request will follow redirection automatically (fixed a bug in Reddit Extractor, at least)

Add Redirect plugin

---

composer.json
composer.lock

Following https://github.com/j0k3r/f43.me/pull/211

Sentry 3 isn't supported by Monolog yet

---

app/config/config_prod.yml
composer.json
composer.lock
phpstan.neon
phpunit.xml.dist

Use Sentry 3.0

---

src/AppBundle/Extractor/Twitter.php
tests/AppBundle/Extractor/TwitterTest.php

Looks like they recently went to 18+
Need to update the regex accordingly.

Fix Twitter ID length

---

docker/Dockerfile-php7.2
docker/launch-f43me.sh
web/app_dev.php

- Enable apcu
- Fix hard coded version of ruby
- Cleanup the image at the end
- Display link to browse the app once images are up
- Allow private IPs to use the `app_dev.php` entry point

Update docker image

---

src/AppBundle/Extractor/Gfycat.php
tests/AppBundle/Extractor/GfycatTest.php

Better iframe for Gfycat

---

Makefile
composer.lock
src/AppBundle/Resources/views/Feed/_favicon.html.twig
src/AppBundle/Resources/views/Feed/index.html.twig
src/AppBundle/Resources/views/Feed/public.html.twig
src/AppBundle/Resources/views/layout.html.twig

Improve public page

---

.travis.yml
app/config/config.yml
composer.json
composer.lock

See https://github.com/doctrine/DoctrineBundle/pull/1059

Avoid deprecated message by using a new strategy

---

.travis.yml
composer.lock

Cleanup Travis

---

app/config/services.yml
src/AppBundle/Command/FetchItemsCommand.php
tests/AppBundle/Command/FetchItemsCommandTest.php

Not really full, but at least when there are still some message to process.
It'll avoid having a queue with thousands of messages if worker are down.

Avoid flooding the queue with new message when it's full

---

src/AppBundle/Extractor/Github.php

Because it's deprecated now.
See https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

Update the way to auth on GitHub

---

.travis.yml
composer.json
composer.lock
phpstan.neon
symfony.lock

Ditch direct dev deps `php-coveralls`

---

config/packages/httplug.yaml

Mostly when I jumped from Guzzle 5 to 6

Fix timeout configuration

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml

- Properly enable compose cache
- Better name jobs
- Use alpine version of rabbitmq
- change the way to handle coverage (and remove one job)

Change the way to handle coverage

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
composer.lock

Also:
- use `ramsey/composer-install` to handle composer install & cache

Symfony 5.1.9

---

composer.lock
config/packages/prod/monolog.yaml

To avoid having that:
```
-rwxrwxrwx 1 www-data www-data 205G Dec  7 20:19 prod.log
```

Rotate log

---

.env
.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
.gitignore
composer.lock
config/packages/routing.yaml
config/packages/translation.yaml
config/packages/twig.yaml
symfony.lock

Symfony 5.3.2

---

composer.lock
src/Command/FetchItemsCommand.php
src/Command/RemoveItemsCommand.php
src/Extractor/Flickr.php
src/Parser/ParserChain.php

- Variable assignment found within a condition. Did you mean to do a comparison ?
- String concat is not required here; use a single string instead

Fix some issues from Codefactor

---

.env
composer.lock
config/packages/webpack_encore.yaml
package.json
symfony.lock
yarn.lock

Symfony 5.4.10

---

docker/Dockerfile-php7.4
src/Repository/LogRepository.php

Only first date for log where displayed (like only the first log created) instead of the latest one.
Also fix docker image extension requirements.

Fix dashboard chart

---

src/Validator/Constraints/ConstraintRssValidator.php

Looks like the host is down now :(
Fix #1094

Replace `feedvalidator.org`

---

.env
config/packages/twig.yaml
templates/base.html.twig
templates/bundles/TwigBundle/Exception/error404.html.twig

See https://www.cnil.fr/en/qa-cnils-formal-notices-concerning-use-google-analytics

Remove Google Analytics

---

assets/styles/app.scss
assets/theme-switcher.js
templates/base.html.twig
webpack.config.js

Fix top bar in dark mode

---

composer.lock
src/Content/Import.php
src/Xml/SimplePieProxy.php
symfony.lock
tests/Xml/SimplePieProxyTest.php
webpack.config.js

Symfony 5.4.14

---

composer.json
composer.lock
tests/Content/ImportTest.php

Increase lowest version allowed to match new namespace requirement.

Update SimplePie namespace

---

package.json
webpack.config.js
yarn.lock

Use `sass-embedded` instead of `sass`
